### ISSUE TITLE
More color ideas

### ISSUE THREAD

**Issue by 1033Forest** [hanubeki/dake#10]
I have some more color ideas after gray and orange:

Dark teal, dark brown, dark green, dark blue, white, black.

These are reserved for special quantization modes, or the random quantization mode (originally reserved for notes up to 1536th, but won't be implemented). White and black are fallback notes if a note has an unknown or invalid quantization. The other colors are reserved for flat or column colored modes.

**Comment by 1033Forest** [comment]
Another colorization idea: PIU Rhythm
4th = Blue
8th = Red
12th = Pink
16th = Yellow
24th = Purple
32nd = Teal
48th = Orange
64th = Green
96th, 192nd = Gray

Mungyodance
4th = Red
8th = Blue
Triplets = Pink
16th = Yellow
32nd = Orange
64th = Teal
96th, 192nd = Gray

Pulsen Shapes
4th = Blue
8th = Green
12th = Pink
16th = Yellow
24th = Orange
32nd = Purple
48th = Gray (was supposed to be violet but there is no violet)
64th = Teal

**Comment by hanubeki** [comment]
@1033Forest It should belongs to #7, reopen and post them.

**Comment by 1033Forest** [comment]
I am trying to implement 128ths and 384ths into SM 5.1. So 2 new colors to be added: Brown and dark teal.

**Comment by hanubeki** [comment]
Closed as favor of 5.2 thing.
