### ISSUE TITLE
Random colorization

### ISSUE THREAD

**Issue by hanubeki** [hanubeki/dake#11]
@1033Forest said in #5:

> Random: Random colors no matter what quantization each note has (example: 4th can be yellow, while another 4th can be pink). This will also randomly color mines too.

I don't know if random colorization can be implemented.

**Comment by 1033Forest** [comment]
For help on how to implement noteskin params ask Jousway or Kyzentun, they probably know

**Comment by 1033Forest** [comment]
Rnadom quantization is not possible, but it is possible to scramble the noteskin state map so nothing is quantized right

**Comment by 1033Forest** [comment]
So it is technically possible, just every 4th note will be the same color, and so will be every 8th, 12th, etc.

**Comment by 1033Forest** [comment]
This issue can be closed now since random quantization has been added to 5.1 as a standalone modifier that works on any noteskin.
