### ISSUE TITLE
Flat colorization

### ISSUE THREAD

**Issue by 1033Forest** [hanubeki/dake#12]
Colorizations list so far:
Quantize
Column
Split
Alternate
Symmetric
Flat (customizable, makes everything a single color, choose between the 10 colors available)

**Comment by hanubeki** [comment]
I will consider to implement customize color not only for Flat but also Split, Alternate and Symmetric.

**Comment by 1033Forest** [comment]
Also customize column colors? So for example you could have left=red, down=yellow, up=blue, and right=green, like a rock band drum set.

**Comment by hanubeki** [comment]
I was not thought about customizable column color.

**Comment by hanubeki** [comment]
https://github.com/hanubeki/noteskin-hanubeki/commit/47284ab858b1856659e64e50d4b6109f631b566e

**Comment by hanubeki** [comment]
https://github.com/hanubeki/noteskin-hanubeki/commit/d9f2661e4ba15a1971c84bdd6fe68db24631f414

**Comment by 1033Forest** [comment]
What is tertiary color for? I only see primary and secondary working...

**Comment by hanubeki** [comment]
Tertiary is for Split coloring with odd column.

**Comment by 1033Forest** [comment]
So for games like pump?

**Comment by hanubeki** [comment]
Yes

**Comment by 1033Forest** [comment]
If I put split scroll mod on a game with an odd number of columns, there will be more columns scrolling down than up. Alternate, more scrolling up than down (unless reverse + alternate)

**Comment by 1033Forest** [comment]
Anyways, these colorizations are working well.
