### ISSUE TITLE
5.1+ graphics

### ISSUE THREAD

**Issue by 1033Forest** [hanubeki/dake#14]
These do not need to be made yet, but later on when 5.1 gets a final release and I start production of 5.1+.

New arrow types: Shock arrows, hidden arrows, potions (once I think of more I will say them here)
Color the reserved arrows, to support quantizations up to 1536th (5.1+ only)

Keep this issue open until 5.1+ gets released.

**Comment by hanubeki** [comment]
Hidden arrows: actually not displayed or transparent in editor?
It can be done by using diffusealpha() without createing new image.

**Comment by 1033Forest** [comment]
Transparent in editor, not displayed in gameplay

**Comment by 1033Forest** [comment]
Shock arrow: Light blue arrow, with lightning on it (I think a separate graphic would need to be created for each one)
Potion: Blue square with a potion icon on it (I think just a potion icon is enough)

**Comment by hanubeki** [comment]
Is potions from PIU?

**Comment by 1033Forest** [comment]
Yes they are from SM AMX, which I will port to my 5.1+ soon

**Comment by hanubeki** [comment]
Potions in noteskin-hanubeki might be heart or red cross in white circle if potion has no effect other than increase life.

**Comment by 1033Forest** [comment]
Potion doesn't do anything in AMX. I will try to make it in 5.1+ to increase life.

**Comment by hanubeki** [comment]
I decided to don't implement note type that not implemented in official branch of SM5.1.
