### ISSUE TITLE
Create image for gem/HOPO, guitar mode

### ISSUE THREAD

**Issue by 1033Forest** [hanubeki/dake#17]
Gem and HOPO are 2 new note types in guitar hero mode being implemented soon.

Gem: Normal tap note in Guitar Hero (works on any gametype and not just guitar) (has a shiny look)
HOPO: Hammer on/pull off note (has a brighter/shiny look)

Notes for guitar mode: Fret1, Fret2, Fret3, Fret4, Fret5, Strum

Column colors: Green, red, yellow, blue, orange (in that order). Strums purple.

**Comment by hanubeki** [comment]
I don't think guitar mode to be implemented, because codes for HOPO was removed from SM5.

**Comment by 1033Forest** [comment]
Mikex5 is making a new guitar mode and will add it back to SM5 later

**Comment by 1033Forest** [comment]
For the frets, circles can be used. For the open strum, a 5 circle long wide note can be used

**Comment by hanubeki** [comment]
![_fret and hopo 2x1 doubleres](https://cloud.githubusercontent.com/assets/6897531/17546838/efc58e2e-5f1e-11e6-8eca-86bfe538ade1.png)
Sorry hanubeki is 2D noteskin.

**Comment by 1033Forest** [comment]
Yeah that can be used.

**Comment by hanubeki** [comment]
I added guitar notes for OutFox in https://github.com/hanubeki/noteskin-hanubeki/commit/49972eb78dd7e1b0d21e5d52b6183af66842c65d so you can test that.

**Comment by hanubeki** [comment]
Closing as of https://github.com/hanubeki/noteskin-hanubeki/commit/20e385b85290dc1e2016c6737bd5b32f9019dc81
