### ISSUE TITLE
Halving Hold/Roll/CPHold image size

### ISSUE THREAD

**Issue by hanubeki** [hanubeki/dake#18]
Height of Hold/Roll/CPHold image can be halved and it may helps implement quantized hold #15.

**Comment by hanubeki** [comment]
![_left roll 2x1 doubleres](https://cloud.githubusercontent.com/assets/6897531/17558318/2b65f7d0-5f55-11e6-8999-9c932e7e7fe2.png)
Before and after.

**Comment by hanubeki** [comment]
Oops... image size for quantized hold will still exceed Stepmania's texture limit. (512x3072, >2048px)

**Comment by hanubeki** [comment]
or rearrange hold image layout?

**Comment by 1033Forest** [comment]
How did you know 2048 is the highest that can be supproted

**Comment by hanubeki** [comment]
Graphics/Sound Options -> Texture Resolution.

**Comment by 1033Forest** [comment]
I have a noteskin that is 2304 x 1152 (5.0 noteskin and the image still works)
