### ISSUE TITLE
Port the NoteSkin for 5.1

### ISSUE THREAD

**Issue by hanubeki** [hanubeki/dake#2]
Here's Kyzentun's post.
http://zenius-i-vanisher.com/v5.2/thread?threadid=7864

I will consider port the noteskin after he finished new noteskin system.

**Comment by hanubeki** [comment]
~~TODO~~ completed: recreate hold graphics for new noteskin system
334 images -> 41 images

**Comment by hanubeki** [comment]
NoteSkin.lua will be separated to 4 parts, but better than ~400 .lua/.redir's.

**Comment by hanubeki** [comment]
I will set supports_all_buttons false since the noteskin does not support lights gametype.

**Comment by hanubeki** [comment]
Schedule:
Start porting to 5.1.0: ~~December 2015 or later~~ Nov 06 2015.

**Comment by hanubeki** [comment]
alpha 1: http://www.geocities.jp/cbrk803832/hanubeki-sm51-alpha1.zip

**Comment by hanubeki** [comment]
Known issues
- ~~Hold image width is shrinked by column width.~~
  - Using negative padding to fix this issue.
- Active hold head has offset if Visual Delay is set.
- ~~Receptor outline does not animate.~~
- ~~ds3ddx: HandUp/HandDown doesn't overlap.~~
  - Using custom_x for ds3ddx.
- ~~Crash when attempt to play beat-double5 chart.~~

Following problems are not confirmed in alpha 2:
- ~~Crash while playing Springtime pump-single Expert (bundled with SM5)~~

**Comment by hanubeki** [comment]
TODO:
- ~~Fallback Hold/Roll images~~
- ~~Custom position for ds3ddx (requires post-alpha2 build)~~
- ~~Color Type: Quantize, Column, Split, Alternate, Symmetric~~
  - [en] Choose coloring method of note.
  - [ja] ノートの色付け方法を選択します。
  - Alternate and Symmetric are same way if column number is odd.
- ~~Note Type: Normal, Bar (Narrow), Bar (Wide), Circle~~
  - [en] Choose shape of note.
  - [ja] ノートの形状を選択します。
- ~~Lift Type: Octagon, Arrow~~
  - [en] Choose shape of lift.
  - [ja] リフトの形状を選択します。
  - Using "Arrow" with Split/Alternate/Symmetric coloring is not recommended.
- ~~(beat) Scratch Side: Left, Right~~
  - [en] Choose side of scratch.
  - [ja] スクラッチの位置を選択します。
  - Consider to implement after incorrect button in beat-*5 is fixed
  - It will require post-alpha2 build.

**Comment by hanubeki** [comment]
alpha 2: http://www.geocities.jp/cbrk803832/hanubeki-sm51-alpha2.zip
- Fix Hold image width by using negative padding
- Fix ds3ddx "image for handup not found".

**Comment by hanubeki** [comment]
alpha 3: http://www.geocities.jp/cbrk803832/hanubeki-sm51-alpha3.zip
- Support kickbox (thanks Kyzentun)

**Comment by hanubeki** [comment]
alpha 4: http://www.geocities.jp/cbrk803832/hanubeki-sm51-alpha4.zip
- Add skin_parameters to noteskin.lua (not tested)
- Add some variant of noteskin

**Comment by hanubeki** [comment]
alpha 5: http://www.geocities.jp/cbrk803832/hanubeki-sm51-alpha5.zip
- Add hack for ds3ddx
- Fix hanubeki-noquant receptor/glow

**Comment by hanubeki** [comment]
alpha 6: http://www.geocities.jp/cbrk803832/hanubeki-sm51-alpha6.zip
- Add split, alternate, symmetry coloring (for bar32/bar64/circle).

**Comment by JOELwindows7** [comment]
dude, the receptor is failed after SM5.1a2

**Comment by hanubeki** [comment]
unfortunately, development is suspended because my PC is broken. sorry.

2016/04/17 (日) 20:48 JOELwindows7 notifications@github.com:

> dude, the receptor is failed after SM5.1b
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hanubeki/noteskin-hanubeki/issues/2#issuecomment-211005825
> 
> ## 

Regards,
はぬべき (hanubeki)

**Comment by JOELwindows7** [comment]
@hanubeki ARRRRGH! Dude! That's why there's  no update.
Anyway sorry to hear that, I hope you have you PC back working well, so I can have your universal noteskin working and inspiration working ;)

**Comment by hanubeki** [comment]
alpha 7: http://www.geocities.jp/cbrk803832/hanubeki-sm51-alpha7.zip
- Now supports 5.1 alpha 2
- Add Note Color and Note Type noteskin params
- Merge noteskins to single folder
  - Note: **Please delete old _hanubeki-&#42;_ folder before update**.

My PC is (temporary?) back!

**Comment by hanubeki** [comment]
GitHub repository is now updated for 5.1 alpha.

**Comment by hanubeki** [comment]
Issue closed, but any comments about 5.1 are still welcome.

**Comment by hanubeki** [comment]
#16: graphics for additional notes not implemented at 1 Aug 2016.
