### ISSUE TITLE
Replace use of newskin calls for compatibility

### ISSUE THREAD

**Issue by 1033Forest** [hanubeki/dake#20]
Replace any references of "newskin" in the lua files with "noteskin".
This will make it compatible with the latest, 5.1 alpha 3. where the old noteskin system has been phased out completely. So the newskin calls are now deprecated.

**Comment by hanubeki** [comment]
Already done in https://github.com/hanubeki/noteskin-hanubeki/commit/b2be2e47b491ddc78cbb0df4331a20f134b7ea8f
