### ISSUE TITLE
Request: Compatible for Etterna

### ISSUE THREAD

**Issue by kowith337** [hanubeki/dake#24]
I've downloaded 5.0 Final version and install in Etterna, but seems like the noteskin didn't show up and revert to default sm5 noteskin and also show this error.

![2020-08-15_174629](https://user-images.githubusercontent.com/16535467/90310841-7baae900-df1f-11ea-899e-2acf78dbb8aa.jpg)

![2020-08-15_175140](https://user-images.githubusercontent.com/16535467/90310895-0be92e00-df20-11ea-9ceb-702c305ac3c1.jpg)

**Comment by hanubeki** [comment]
Try cloning current branch; I already eliminated usage of cmd() which is deprecated, and confirmed current branch works on Etterna.

**Comment by kowith337** [comment]
Confirm it's work on 0.70.3, thanks for your guide.
