### ISSUE TITLE
Support for "horizon" game

### ISSUE THREAD

**Issue by hanubeki** [hanubeki/dake#25]
I will start work once https://github.com/stepmania/stepmania/pull/2051 is merged.
I think no additional graphic is needed for this.

**Comment by aeubanks** [comment]
I have a fork [here] that I've been using if you'd like to use it, but feel free to do a better job than me :)

[here]: https://github.com/aeubanks/noteskin-hanubeki/commit/e2617bd3a58191e7baee0027694c08b3b108ae7e

**Comment by hanubeki** [comment]
I added something in https://github.com/hanubeki/noteskin-hanubeki/commit/49972eb78dd7e1b0d21e5d52b6183af66842c65d

**Comment by hanubeki** [comment]
I'm sorry, but non-OutFox build/fork of StepMania is not supported anymore.
