### ISSUE TITLE
New noteskin color params

### ISSUE THREAD

**Issue by 1033Forest** [hanubeki/dake#5]
These could be added:
Halve - Like quantize but "halves" the note colors, so:
4th - Red
8th - Red
12th - Green
16th - Blue
24th - Green
32nd - Yellow
48th - Purple
64th - Teal
192nd - Not affected

Random: Random colors no matter what quantization each note has (example: 4th can be yellow, while another 4th can be pink). This will also randomly color mines too.

And params to enable/disable quantized mines

**Comment by hanubeki** [comment]
I don't know if random note color can be implemented.
Otherwise, those can be implemented. I will consider to implement.

**Comment by 1033Forest** [comment]
I am thinking of more quantizations based on speed mod.
Halved noteskin, makes it look like you are playing at double BPM.
Thirdsed: Regular quantizations, but removes triplet colors (12th=red, 24th=blue, 48th=yellow). This will make it look like playing at 3x BPM.
Quartered: 4th-16th red, 24th and 48th green, 32nd blue, 64th yellow. Looks like playing at 4x BPM.

3.9 quantization: Changes colors to 3.9 style, so:
4th=Red
8th=Blue
12th=Purple
16th=Yellow
24th=Pink
32nd=Orange
48th=Teal
64th=Green
96th=Light green
192nd=Gray

Flat: Turns all notes gray, or any single color
Solo: 4ths orange, 8ths blue, triplets pink, others purple
ITG style: Changes colors to ITG. 4th=orange, 8th=blue, triplets purple, 16th=green, 32nd=yellow, 64th=teal.
DDR style: 4ths red, 8ths blue, 16ths yellow, everything else green.
If I can think of anything more I'll post here.

**Comment by hanubeki** [comment]
Mine Color: Completed in https://github.com/hanubeki/noteskin-hanubeki/commit/60f07877649f415bab68d02c99cfbd97aee7df5e

**Comment by 1033Forest** [comment]
Can quantized lift octagons be added too? Lift color can also be added

**Comment by 1033Forest** [comment]
There is a new hold type being implemented soon called checkpoint hold (not implemented yet). For this one the graphic can be purple striped hold.

Checkpoint hold is a PIU style hold that works on any game type. What it does is, while held adds to combo as long as the hold is being held. It is blue in the zenbuquan noteskin.

**Comment by hanubeki** [comment]
tagged low priority because I won't use this feature

**Comment by hanubeki** [comment]
Close this issue, You should report separate issue each feature you want.
