### ISSUE TITLE
Quantize multiplier

### ISSUE THREAD

**Issue by hanubeki** [hanubeki/dake#6]
@1033Forest said in #5:

> I am thinking of more quantizations based on speed mod.
> Halved noteskin, makes it look like you are playing at double BPM.
> Thirdsed: Regular quantizations, but removes triplet colors (12th=red, 24th=blue, 48th=yellow). This will make it look like playing at 3x BPM.
> Quartered: 4th-16th red, 24th and 48th green, 32nd blue, 64th yellow. Looks like playing at 4x BPM.

**Comment by hanubeki** [comment]
This feature might not be compatible with #7.

**Comment by hanubeki** [comment]
https://github.com/hanubeki/noteskin-hanubeki/commit/88066810fd1a0389a84fe157dc87ceda8112e8b8
https://github.com/hanubeki/noteskin-hanubeki/commit/f76b7e365576295c2d17567dc804feeb990151da

**Comment by hanubeki** [comment]
Close this after you verified behavior, @1033Forest.

**Comment by hanubeki** [comment]
https://github.com/hanubeki/noteskin-hanubeki/commit/e4bff702591b9b9e639e7233f30a7b9fc0c7a793

**Comment by 1033Forest** [comment]
Another quantize multiplier: Semi Halved
Same as halved but leaves 24ths and 48ths intact

4th = 4th
8th = 4th
12th = 12th
16th = 8th
24th = 24th
32nd = 16th
48th = 48th
64th = 32nd
96th = 96th
192nd = 192nd

**Comment by hanubeki** [comment]
Closed by #22
