### ISSUE TITLE
Quantize variant

### ISSUE THREAD

**Issue by hanubeki** [hanubeki/dake#7]
@1033Forest said in #5:

> 3.9 quantization: Changes colors to 3.9 style, so:
>  4th=Red
>  8th=Blue
>  12th=Purple
>  16th=Yellow
>  24th=Pink
>  32nd=Orange
>  48th=Teal
>  64th=Green
>  96th=Light green
>  192nd=Gray
> 
> Flat: Turns all notes gray, or any single color
>  Solo: 4ths orange, 8ths blue, triplets pink, others purple
>  ITG style: Changes colors to ITG. 4th=orange, 8th=blue, triplets purple, 16th=green, 32nd=yellow, 64th=teal.
>  DDR style: 4ths red, 8ths blue, 16ths yellow, everything else green.
>  If I can think of anything more I'll post here.

**Comment by 1033Forest** [comment]
"Bold" color scheme (4.0)
4th = Green
8th = Red
12th = Blue
16th = Yellow
24th = Purple
32nd = Teal
48th = Pink
64th = Orange

**Comment by hanubeki** [comment]
I will add "Quantize Mode" NoteSkin Parameter if I implement this.

**Comment by hanubeki** [comment]
This feature might not be compatible with #6.

**Comment by 1033Forest** [comment]
Merge quantize mode and multiplier together, that way, we will have a list of options:
Halved
Thirdsed
Quartered
3.9
4.0
Flat
Solo
ITG
DDR

**Comment by 1033Forest** [comment]
For "vivid" type, it is color cycling. Each note, colors at a different frame.
Flat vivid, all notes color at same frame. Similar to default DDR noteskin, or default 3.9 version.

**Comment by hanubeki** [comment]
I won't add animated color such as vivid.

**Comment by 1033Forest** [comment]
Actually halved, thirdsed, quartered can be combined with any quantize variant to halve, third, or quarter a different quantize variant. 

Quantize Multiplier
1x (default)
2x (halved)
3x (thirdsed)
4x (quartered)

Quantize Variant
3.9
4.0
4.0 Bold
Flat
Solo
ITG
DDR

**Comment by hanubeki** [comment]
I made the code for generate state table for Multiplier and Variant.
I will push that after some testing.

**Comment by 1033Forest** [comment]
OK

**Comment by hanubeki** [comment]
https://github.com/hanubeki/noteskin-hanubeki/commit/88066810fd1a0389a84fe157dc87ceda8112e8b8
https://github.com/hanubeki/noteskin-hanubeki/commit/f76b7e365576295c2d17567dc804feeb990151da

**Comment by hanubeki** [comment]
Close this after you verified behavior, @1033Forest.

**Comment by hanubeki** [comment]
https://github.com/hanubeki/noteskin-hanubeki/commit/baf2a14645a5bdbfcc70aca854505e307a22906d
https://github.com/hanubeki/noteskin-hanubeki/commit/52ad9c7880865112ae3a7c35aeaad01fe15cf3bb

**Comment by 1033Forest** [comment]
Everything is proper.

**Comment by 1033Forest** [comment]
Another colorization idea: PIU Rhythm
4th = Blue
8th = Red
12th = Pink
16th = Yellow
24th = Purple
32nd = Teal
48th = Orange
64th = Green
96th, 192nd = Gray

Mungyodance
4th = Red
8th = Blue
Triplets = Pink
16th = Yellow
32nd = Orange
64th = Teal
96th, 192nd = Gray

Pulsen Shapes
4th = Blue
8th = Green
12th = Pink
16th = Yellow
24th = Orange
32nd = Purple
48th = Gray (was supposed to be violet but there is no violet)
64th = Teal

**Comment by hanubeki** [comment]
What about "Pulsen Shapes"?
I never played Pulsen.

**Comment by 1033Forest** [comment]
Color scheme from Pulsen game if a shape noteskin is used (blockie, coin, or lantern).

**Comment by hanubeki** [comment]
https://github.com/hanubeki/noteskin-hanubeki/commit/0b6264cab3bc8dd85d5cb3c9a6ff606745666558

**Comment by 1033Forest** [comment]
Keeping this open in case I think of any new quantization ideas.

**Comment by 1033Forest** [comment]
"48th = Gray (was supposed to be violet but there is no violet)"
Reminds me of peanuts character Violet Gray.

New color scheme: Point (based on another noteskin with the same name)
4th = Gray
8th = Pink
12th = Green
16th = Blue
24th = Yellow
32nd = Purple
48th = Light Green
64th = Orange

Katze Note (Based on dieKatze88's noteskin)
4th = Red
8th = Blue
12th = Green
16th = Yellow
24th = Pink
32nd = Orange
48th = Teal
64th = Purple
192nd = Gray

**Comment by 1033Forest** [comment]
My namesake color scheme (this one, will be called 1033Forest)
4th = Red
8th = Blue
12th = Pink
16th = Yellow
24th = Orange
32nd = Green
48th = Gray
64th = Teal

Block (based on block noteskin for 3.9)
4th = Blue
8th = Green
12th = Red
16th = Yellow
24th = Orange
32nd = Teal
48th = Pink
64th = Light Green
192nd = Purple

**Comment by hanubeki** [comment]
Closed as favor of 5.2 thing.
